name: Romashka Build System
on: [workflow_dispatch, push]

jobs:
  build-pack:
    runs-on: ubuntu-latest # На линуксе быстрее и стабильнее для упаковки
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create App Structure
        run: |
          mkdir -p RomashkaVPN_Payload
          cp main.py RomashkaVPN_Payload/
          cp romashka.png RomashkaVPN_Payload/
          if [ -f requirements.txt ]; then cp requirements.txt RomashkaVPN_Payload/; fi
          # Создаем пустой файл для структуры
          touch RomashkaVPN_Payload/Studio26_Certified.txt

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Romashka_VPN_Ready_To_Install
          path: RomashkaVPN_Payload/
          retention-days: 1
